name: Close Stale Issues
on:
  schedule:
    - cron: "0 0 * * *" 

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - name: Close stale issues
        uses: actions/stale@v8
        with:
          days-before-stale: 30  
          days-before-close: 7   
          stale-issue-label: "stale"
          stale-issue-message: "This issue has been marked as stale due to inactivity. If no further activity occurs, it will be closed in 7 days."
          close-issue-message: "This issue has been closed due to inactivity. Please reopen if needed."
          exempt-issue-labels: "important,bug" 
